/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sun_myapplication_MyLibrary */

#ifndef _Included_com_example_sun_myapplication_MyLibrary
#define _Included_com_example_sun_myapplication_MyLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sun_myapplication_MyLibrary
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sun_myapplication_MyLibrary_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
